<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>

		<Nullable>enable</Nullable>

		<GenerateEvergineContent>True</GenerateEvergineContent>
		<GenerateEvergineAssets>False</GenerateEvergineAssets>
		<GenerateEvergineScenesCode>True</GenerateEvergineScenesCode>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Evergine.Common" Version="2025.10.21.3204" />
		<PackageReference Include="Evergine.Components" Version="2025.10.21.3204" />
		<PackageReference Include="Evergine.Framework" Version="2025.10.21.3204" />
		<PackageReference Include="Evergine.Mathematics" Version="2025.10.21.3204" />
		<PackageReference Include="Evergine.Bullet" Version="2025.10.21.3204" />
		<PackageReference Include="Evergine.Targets" Version="2025.10.21.3204" />
		<PackageReference Include="Evergine.CodeScenes" Version="2025.10.21.3204" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Navigation\Data\Resources\ROADS.geojson" />
		<EmbeddedResource Include="Navigation\Data\Resources\POINTS.geojson" />
	</ItemGroup>

</Project>
