<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../RescuAR/RescuAR.csproj" AdditionalProperties="GenerateEvergineContent=False;GenerateEvergineScenesCode=False" />
    <Compile Include="../../RescuAR.MAUI/Services/ArCoreRunIntent.cs" Link="ArCoreRunIntent.cs" />
    <Compile Include="../../RescuAR.MAUI/Services/Flood/FloodDepthVisualizationService.cs" Link="FloodDepthVisualizationService.cs" />
  </ItemGroup>
</Project>
